apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring-lab.labels" . | nindent 4 }}
    app.kubernetes.io/name: app
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: 5000
      protocol: TCP
      {{- if eq .Values.app.service.type "NodePort" }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
