apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring-lab.labels" . | nindent 4 }}
    app.kubernetes.io/name: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.prometheus.service.port }}
        isDefault: true
        editable: true
        jsonData:
          timeInterval: "5s"
          httpMethod: POST
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.jaeger.service.port }}
        editable: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring-lab.labels" . | nindent 4 }}
    app.kubernetes.io/name: grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: "Monitoring Lab"
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: false
