apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring-lab.labels" . | nindent 4 }}
    app.kubernetes.io/name: otel-collector
spec:
  type: {{ .Values.otelCollector.service.type }}
  selector:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: prom-exporter
      port: 8889
      targetPort: 8889
      protocol: TCP
    - name: health
      port: 13133
      targetPort: 13133
      protocol: TCP
    - name: zpages
      port: 55679
      targetPort: 55679
      protocol: TCP
